### ISSUE TITLE
create snakemake workflow

### ISSUE THREAD

**Issue by backeb** [c-scale-community/use-case-hisea#43]
Implementing first version in https://github.com/c-scale-community/use-case-hisea/tree/Snakefile_python2docker

## Initial to do's:
- [x] make dates in [Snakefile](https://github.com/c-scale-community/use-case-hisea/blob/main/workflow/Snakefile) dynamic
- [x] specify `data_loc` in `config.yml`
- [x] specify `.pli` files in `config.yml`
- [x] always create as new folder by date when running the workflow

### make snakemake rules dynamic
- [x] for the `shell:` rules, replace `{date.today().strftime('%Y-%m-%d')}` with `$(date +%Y-%m-%d)` or `$(date --iso-8601)`

### check rules
- [x] rule set_date_range:
- [x] rule download_era5:
- [x]  rule download_cmems_physics:
- [x]  rule download_cmems_biogeochemistry:
- [x]  rule preprocess_era5:
- [x]  rule create_random_DFMWAQ_folder:
- [x]  rule preprocess_cmems:
- [x]  rule check4fes2012_files:
- [x]  rule preprocess_fes2012:
- [x]  Move data to preprocessing/tides folder
- [x]  rule copy_preprocessed_data_to_model_input_folder:
- [x]  rule update_mdu_file:
- [x] rule workaround_update_RadSurf_daily:
- [x]  rule run_delft3dfm:
- [x] move data to rst, map, etc folders
- [x]  rule move_raw_data_to_output_folder:
- [x]  rule cleanup_model_folder:

### workarounds
- [x] add snakemake rule in [Snakefile](https://github.com/c-scale-community/use-case-hisea/blob/Snakefile_python2docker/workflow/Snakefile) for [RadSurf_daily.tim workaround](https://github.com/c-scale-community/use-case-hisea/blob/main/scripts/workarounds/update_existing_RadSurf_daily_dot_tim.py)
- [x] test if delft3dfm runs with workaround

### other tasks
- [x] #49
- [x] #50

## Updated to do's 30 March
Test a couple ways to run:
- [ ] snakemake --cores 1 all
- [ ] snakemake --cores 4 all
- [ ] snakemake --cores 16 all

**Comment by backeb** [comment]
Hi @sebastian-luna-valero and @lorincmeszaros, 

I've created a first near-complete version of the Snakefile. You can find it [here](https://github.com/c-scale-community/use-case-hisea/tree/Snakefile_python2docker/workflow) if you want to test it. Note I've been working in `Snakefile_python2docker` branch.

My next step is to make the `23-01-23` date that I use throughout the `Snakefile`, e.g. in the `*.log`, `*.done` and foldernames **dynamic**. The idea I have is that if I run the workflow today it creates e.g. `23-03-03_blah_blah.log`, `23-03-03_blah_blah.done` and foldernames with today's date.

This way we create a new folder each time we run the workflow, i.e. we can keep the input data and model output for analysis later.

There are probably also improvements that can be made, e.g. snakemake can automatically create folders if they are defined under `output:` in the `Snakefile`.

Let me know if it works for you. And what improvement suggestions you have.

Thanks
Björn

**Comment by backeb** [comment]
@backeb double check that all the rules work, and also that the necessary folders are created if they don't exist.

Check
- [ ] rule download_era5:
- [ ] rule download_cmems_physics:
- [ ] rule download_cmems_biogeochemistry:
- [ ] rule preprocess_era5:
- [ ] rule create_random_DFMWAQ_folder:
- [ ] rule preprocess_cmems:
- [ ] rule preprocess_fes2012:
- [ ] rule copy_preprocessed_data_to_model_input_folder:
- [ ] rule run_delft3dfm:
- [ ] rule cleanup_model_input_folder:
- [ ] rule move_raw_data_to_output_folder:
- [ ] rule cleanup_model_folder:
- [ ] rule postprocess_raw_data:

**Comment by backeb** [comment]
@sebastian-luna-valero, @lorincmeszaros there's an error with the `preprocess_fes2012` rule, am working on it.

**Comment by sebastian-luna-valero** [comment]
Thanks @backeb !

My comments so far:
* Replace `ouput` with `output` in  https://github.com/c-scale-community/use-case-hisea/blob/Snakefile_python2docker/workflow/Snakefile#L284
* In `rule download_era5`, the default location of the `.cdsapirc` file should be generic; i.e., `${HOME}/.cdsapirc`. I see that's not easy to do, but I will try to find a solution.

**Comment by backeb** [comment]
I'm thinking we could also specify some folders in `config.yml`

**Comment by backeb** [comment]
Try the following to make `2023-01-23`, `--date_min {params.date_min}` and `--date_max {params.date_max}` dynamic

```
import datetime

# Compute the current date
now = datetime.datetime.now()
current_date = now.strftime("%Y-%m-%d")

# Compute the date range
delta = datetime.timedelta(days=7)
date_min = (now - delta).strftime("%Y-%m-%d")
date_max = now.strftime("%Y-%m-%d")

rule download_era5:
    input:
        "/home/centos/.cdsapirc"
    output:
        touch("workflow/logs/{current_date}_download_era5.done")
    log:
        "workflow/logs/{current_date}_download_era5.log"
    params:
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = date_min,
        date_max = date_max
    shell:
        """
        sudo docker run \
            -v {input}:/root/.cdsapirc \
            -v /home/centos/data/download/{current_date}:/data \
            download-input python download_era5.py \
                --longitude_min {params.lon_min} \
                --longitude_max {params.lon_max} \
                --latitude_min {params.lat_min} \
                --latitude_max {params.lat_max} \
                --date_min {params.date_min} \
                --date_max {params.date_max}
        """
```

**Comment by backeb** [comment]
> 

`rule postprocess_raw_data:` give the following error:
```
Traceback (most recent call last):
  File "/root/nc2regularGrid_listComprehension.py", line 1, in <module>
    from dfm_tools.get_nc import get_netdata, get_ncmodeldata
ImportError: cannot import name 'get_netdata' from 'dfm_tools.get_nc' (/opt/conda/envs/env/lib/python3.8/site-packages/dfm_tools/get_nc.py
```

Likely to do with changes made in `dfm_tools`.

For now have commented out `rule postprocess_raw_data:` in the Snakefile.

**Comment by backeb** [comment]
@backeb make all the below rules dynamic following the approach in https://github.com/c-scale-community/use-case-hisea/issues/43#issuecomment-1460331411 

- [ ] rule download_era5:
- [ ] rule download_cmems_physics:
- [ ] rule download_cmems_biogeochemistry:
- [ ] rule preprocess_era5:
- [ ] rule create_random_DFMWAQ_folder:
- [ ] rule preprocess_cmems:
- [ ] rule preprocess_fes2012:
- [ ] rule copy_preprocessed_data_to_model_input_folder:
- [ ] rule run_delft3dfm:
- [ ] rule cleanup_model_input_folder:
- [ ] rule move_raw_data_to_output_folder:
- [ ] rule cleanup_model_folder:

**Comment by sebastian-luna-valero** [comment]
Thanks!

My comments:
* although the idea to automatically capture the current date is cool, I am not sure I like having python code in the `Snakefile` for this purpose...
* also, would it not be better to specify the desired date via an input parameter? instead of taking it automatically?
* I am sorry I didn't have the time to look into this, but I still believe that we should have something like `cdsapirc_loc: ${HOME}/.cdsapirc` instead of `cdsapirc_loc: /home/centos/.cdsapirc` in `config.yml`. Currently I am having issues when using environment variables in the `config.yml`, but I would like to understand why.

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/snakemake/snakemake/issues/2166

**Comment by backeb** [comment]
Thanks @sebastian-luna-valero 

Some quick responses:

> * although the idea to automatically capture the current date is cool, I am not sure I like having python code in the `Snakefile` for this purpose...

Maybe this is a _pythonic_ way of doing things? 😀
It would be nice to maybe leverage `bash` and use something like `$(date)` in the `config.yml` instead.

> * also, would it not be better to specify the desired date via an input parameter? instead of taking it automatically?

The reason I'm doing it like this is because I want to run the workflow every day, and every day create a 5-day forecast. This seemed the easiest way to "automate" that.

> * I am sorry I didn't have the time to look into this, but I still believe that we should have something like `cdsapirc_loc: ${HOME}/.cdsapirc` instead of `cdsapirc_loc: /home/centos/.cdsapirc` in `config.yml`. Currently I am having issues when using environment variables in the `config.yml`, but I would like to understand why.

No worries, I'm also interested in understanding that, since that would help us to also define dates automatically in the `config.yml` instead of having to switch between configuring things in `config.yml` and the `Snakefile`.

**Comment by backeb** [comment]
Maybe an alternative is to create ‘get_from_config.py’ or rule that creates all the variables needed for the rest of the workflow. That way all the config stuff is kept centrally within ‘config.yml’

**Comment by backeb** [comment]
> xref: [snakemake/snakemake#2166](https://github.com/snakemake/snakemake/issues/2166)

potential solution: https://github.com/snakemake/snakemake/issues/2166#issuecomment-1463520411

**Comment by backeb** [comment]
I've made a small command-line tool to update `RadSurf_daily.tim`: I've put it in [scripts/workarounds/](https://github.com/c-scale-community/use-case-hisea/tree/main/scripts)[update_existing_RadSurf_daily_dot_tim.py](https://github.com/c-scale-community/use-case-hisea/blob/main/scripts/workarounds/update_existing_RadSurf_daily_dot_tim.py).

- [ ] add snakemake rule in [Snakefile](https://github.com/c-scale-community/use-case-hisea/blob/Snakefile_python2docker/workflow/Snakefile)

**Comment by sebastian-luna-valero** [comment]
ok, change below works to make '${HOME}/.cdsapirc' portable.

```bash
$ git diff
diff --git a/workflow/Snakefile b/workflow/Snakefile
index ede1b86..e628ebd 100644
--- a/workflow/Snakefile
+++ b/workflow/Snakefile
@@ -2,12 +2,12 @@ configfile: "workflow/config.yml"
 
 rule download_era5:
     input:
-        "/home/centos/.cdsapirc"
     output:
         touch("workflow/logs/2023-01-23_download_era5.done")
     log:
         "workflow/logs/2023-01-23_download_era5.log"
     params:
+        cdsapirc = lambda wc: config['cdsapirc'],
         lon_min = config['lon_min'],
         lon_max = config['lon_max'],
         lat_min = config['lat_min'],
@@ -17,7 +17,7 @@ rule download_era5:
     shell:
         """
         sudo docker run \
-            -v {input}:/root/.cdsapirc \
+            -v {params.cdsapirc}:/root/.cdsapirc \
             -v /home/centos/data/download/2023-01-23:/data \
             download-input python download_era5.py \
                 --longitude_min {params.lon_min} \
diff --git a/workflow/config.yml b/workflow/config.yml
index 08d5fb2..27e6dbd 100644
--- a/workflow/config.yml
+++ b/workflow/config.yml
@@ -1,3 +1,4 @@
+cdsapirc: '${HOME}/.cdsapirc'
```

Could you please test?

**Comment by backeb** [comment]
Using wildcards in Snakefile: https://github.com/snakemake/snakemake/issues/2166#issuecomment-1466123779

**Comment by backeb** [comment]
Hi @sebastian-luna-valero

I'm trying to do something like
```
rule set_pythonpath:
    params:
        home = lambda wc: "${HOME}"
    shell:        
    """
        echo 'export PYTHONPATH="{params.home}/use-case-hisea/scripts/workflow_helpers:{params.home}/use-case-hisea/scripts/delft3dfm_helpers"' >> ~/.bashrc && \        
        source ~/.bashrc
    """
```
but it isn't really working... do you have any idea how I could create a rule that does
```
export PYTHONPATH="${HOME}/use-case-hisea/scripts/workflow_helpers:${HOME}/use-case-hisea/scripts/delft3dfm_helpers
```
so that in subsequent rules I can do 
`from delft3dfm_helpers import get_tref, update_mdu_tstart_tstop` and
`from workflow_helpers import get_date_range`

**Comment by backeb** [comment]
hi again @sebastian-luna-valero,

nevermind, this worked:
```
rule set_pythonpath:
    params:
        home = lambda wc: "${HOME}"
    shell:
        """
        if ! grep -qxF 'export PYTHONPATH="{params.home}/use-case-hisea/scripts/workflow_helpers:{params.home}/use-case-hisea/scripts/delft3dfm_helpers"' ~/.bashrc
        then
            echo 'export PYTHONPATH="{params.home}/use-case-hisea/scripts/workflow_helpers:{params.home}/use-case-hisea/scripts/delft3dfm_helpers"' >> ~/.bashrc && \
            if [[ $- == *i* ]]; then source ~/.bashrc; fi
        else
            echo "PYTHONPATH is already set in .bashrc."
        fi
        """
```

**Comment by backeb** [comment]
@backeb continue with debugging from `snakemake -R download_era5 --cores 1`

**Comment by sebastian-luna-valero** [comment]
What about using `$(date --iso-8601)` instead?

**Comment by backeb** [comment]
> * `$(date +%Y-%m-%d)` or `$(date --iso-8601)`

Hi @sebastian-luna-valero,

found this: https://unix.stackexchange.com/questions/164826/date-command-iso-8601-option

Think I might stick with `$(date +%Y-%m-%d)`

**Comment by backeb** [comment]
> > Thanks @backeb !
> > My comments so far:
> > 
> > * Replace `ouput` with `output` in  https://github.com/c-scale-community/use-case-hisea/blob/Snakefile_python2docker/workflow/Snakefile#L284
> > * In `rule download_era5`, the default location of the `.cdsapirc` file should be generic; i.e., `${HOME}/.cdsapirc`. I see that's not easy to do, but I will try to find a solution.
> 
> Hi @sebastian-luna-valero, thanks for that feedback.
> 
> I've been working on trying to make things more dynamic, below the solution I've developed:
> 
> ```
> configfile: "workflow/config.yml"
> data_dir_path = config['data_dir_path']
> 
> import datetime
> 
> # Get the current date to create folders named for the current to store the data in
> now = datetime.datetime.now()
> current_date = now.strftime("%Y-%m-%d")
> 
> # Get the date range over which to download input data and run the model
> # Note ERA5 data used in this example has a 5-day latency
> date_min = (now - datetime.timedelta(days=10)).strftime("%Y-%m-%d")
> date_max = (now - datetime.timedelta(days=6)).strftime("%Y-%m-%d")
> 
> rule download_era5:
>     input:
>         expand("{cdsapirc_loc}", cdsapirc_loc=config['cdsapirc_loc'])
>     output:
>         expand("workflow/logs/{current_date}_download_era5.done", current_date=current_date)
>     log:
>         expand("workflow/logs/{current_date}_download_era5.log", current_date=current_date)
>     params:
>         lon_min = config['lon_min'],
>         lon_max = config['lon_max'],
>         lat_min = config['lat_min'],
>         lat_max = config['lat_max'],
>         date_min = date_min,
>         date_max = date_max
>     shell:
>         """ 
>         sudo docker run \
>             -v {input}:/root/.cdsapirc \
>             -v {data_dir_path}/download/{current_date}:/data \
>             download-input python download_era5.py \
>                 --longitude_min {params.lon_min} \
>                 --longitude_max {params.lon_max} \
>                 --latitude_min {params.lat_min} \
>                 --latitude_max {params.lat_max} \
>                 --date_min {params.date_min} \
>                 --date_max {params.date_max} && \
>         touch workflow/logs/{current_date}_download_era5.done
>         """
> ```
> 
> and then in `config.yml` I've specified:
> 
> ```
> cdsapirc_loc: "/home/centos/.cdsapirc"
> data_dir_path: "/home/centos/data"
> cmems_uname: myusername
> cmems_pwd: mypassword
> lon_min: 22.5
> lon_max: 24.5
> lat_min: 36.5
> lat_max: 38.5
> ```
> 
> My next step is to apply this to the other rules

The approach I've adopted is a bit different now.

In the `Snakefile` I use the `rule set_date_range:` to update `date_min` and `date_max` in `workflow/config.yml`. The `workflow/config.yml` has the lines
```
################## DO NOT EDIT ANYTHING BELOW THIS LINE ###############################

# update date_min, date_max for each execution of the workflow
date_min: 2023-03-13
date_max: 2023-03-15
```
Everything above the `DO NOT EDIT ANYTHING BELOW THIS LINE` is configurable by the user. The `config.yml` is the central place where all things for the workflow are configured.

**Comment by backeb** [comment]
Added `rule all:`.

Testing a couple ways to run:
1. `snakemake --cores 1 all`
2. `snakemake --cores 4 all`
3. `snakemake --cores 16 all`
